/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

import static java.awt.Frame.MAXIMIZED_BOTH;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import java.awt.Image;
import java.awt.Graphics;
import javax.swing.ImageIcon;

/**
 *
 * @author Bruna Leonel
 */
public class TelaInicial extends javax.swing.JFrame {
    /**
     * Creates new form TelaGerente
     */
    public TelaInicial() {
      initComponents();
      
      setExtendedState(MAXIMIZED_BOTH);
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon= new ImageIcon(getClass().getResource("/Imagem/background2.jpg"));
        Image image= icon.getImage();
        jDesktopPane1 = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        };
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        ClienteManutençao = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        FuncionarioManutenção = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        PeçasManutençao = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Início");

        jDesktopPane1.setBackground(new java.awt.Color(0, 51, 153));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 572, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );

        jMenu4.setText("Clientes");

        ClienteManutençao.setText("Manutenção");
        ClienteManutençao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClienteManutençaoActionPerformed(evt);
            }
        });
        jMenu4.add(ClienteManutençao);

        jMenuBar1.add(jMenu4);

        jMenu1.setText("Funcionários");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        FuncionarioManutenção.setText("Manutenção");
        FuncionarioManutenção.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FuncionarioManutençãoActionPerformed(evt);
            }
        });
        jMenu1.add(FuncionarioManutenção);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Peças");

        PeçasManutençao.setText("Manutençao");
        PeçasManutençao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PeçasManutençaoActionPerformed(evt);
            }
        });
        jMenu3.add(PeçasManutençao);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /*public void MecanicoLogin()
    {
        jMenu1.setEnabled(false);
        jMenu1.setVisible(false);
        jMenu4.setEnabled(false);
        jMenu4.setVisible(false);
        jMenu3.setEnabled(false);
        jMenu3.setVisible(false);
        jMenu5.setEnabled(false);
        jMenu5.setVisible(false);
    }
    public void AtendenteLogin()
    {
        jMenu1.setEnabled(false);
        jMenu1.setVisible(false);
        jMenu2.setEnabled(false);
        jMenu2.setVisible(false);
        jMenu3.setEnabled(false);
        jMenu3.setVisible(false);
    }
    public void GerenteLogin()
    {
        jMenu1.setEnabled(true);
        jMenu1.setVisible(true);
        jMenu2.setEnabled(true);
        jMenu2.setVisible(true);
        jMenu3.setEnabled(true);
        jMenu3.setVisible(true);
        jMenu4.setEnabled(true);
        jMenu4.setVisible(true);
        jMenu5.setEnabled(true);
        jMenu5.setVisible(true);
    }*/
    private void FuncionarioManutençãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FuncionarioManutençãoActionPerformed
        TelaFuncionario tf = new TelaFuncionario();
        jDesktopPane1.add(tf);
        tf.setVisible(true);
    }//GEN-LAST:event_FuncionarioManutençãoActionPerformed

    private void ClienteManutençaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClienteManutençaoActionPerformed
      TelaCliente tc = new TelaCliente();
      jDesktopPane1.add(tc);
      tc.setVisible(true);
    }//GEN-LAST:event_ClienteManutençaoActionPerformed

    private void PeçasManutençaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PeçasManutençaoActionPerformed
        TelaPeças tp = new TelaPeças();
        jDesktopPane1.add(tp);
        tp.setVisible(true);
    }//GEN-LAST:event_PeçasManutençaoActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        
    }//GEN-LAST:event_jMenu1ActionPerformed



   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ClienteManutençao;
    private javax.swing.JMenuItem FuncionarioManutenção;
    private javax.swing.JMenuItem PeçasManutençao;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
