/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import Dao.Conexao;
import Dao.ProdutoDao;
import Model.CadastroProduto;
import Model.CadastroUsuário;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gabriel
 */
public class TelaPeças extends javax.swing.JInternalFrame {
  CadastroProduto produto;
  ProdutoDao pt;
   
    public TelaPeças() {
        pt = new ProdutoDao();
        produto= new CadastroProduto();
        initComponents();
        Show_Clientes();
        centralizarComponente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TxCodProduto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TxDescreveProduto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TxQtdProd = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TxPrecoProd = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TxPrecoProdVenda = new javax.swing.JTextField();
        BtNovo = new javax.swing.JButton();
        BtSalvar = new javax.swing.JButton();
        BtAlterar = new javax.swing.JButton();
        BtExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCliente = new javax.swing.JTable();
        BtPesquisarProd = new javax.swing.JButton();

        setClosable(true);
        setTitle("Cadastro de Produto");

        jLabel1.setText("Cod:");

        TxCodProduto.setEditable(false);

        jLabel2.setText("Descriçao do Produto:");

        jLabel3.setText("Quantidade:");

        TxQtdProd.setEditable(false);

        jLabel4.setText("Preço Pago:");

        TxPrecoProd.setEditable(false);

        jLabel5.setText("Preço Venda Unitario:");

        TxPrecoProdVenda.setEditable(false);

        BtNovo.setText("Novo");
        BtNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtNovoActionPerformed(evt);
            }
        });

        BtSalvar.setText("Salvar");
        BtSalvar.setEnabled(false);
        BtSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSalvarActionPerformed(evt);
            }
        });

        BtAlterar.setText("Alterar");
        BtAlterar.setEnabled(false);

        BtExcluir.setText("Excluir");
        BtExcluir.setEnabled(false);

        tblCliente = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex,int colIndex){
                return false;
            }

        };
        tblCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "descricao", "Quantidade", "Preço Venda"
            }
        ));
        jScrollPane1.setViewportView(tblCliente);

        BtPesquisarProd.setText("Pesquisar");
        BtPesquisarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtPesquisarProdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TxQtdProd)
                            .addComponent(TxCodProduto))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TxDescreveProduto)
                                .addGap(4, 4, 4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(TxPrecoProd, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TxPrecoProdVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(66, 66, 66)
                                        .addComponent(BtAlterar)
                                        .addGap(18, 18, 18)
                                        .addComponent(BtExcluir)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BtNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtSalvar)))
                .addComponent(BtPesquisarProd)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 793, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxDescreveProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtPesquisarProd))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxQtdProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxPrecoProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxPrecoProdVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtNovo)
                    .addComponent(BtSalvar)
                    .addComponent(BtAlterar)
                    .addComponent(BtExcluir))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Cadastro", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Cadastro");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void centralizarComponente() {
        Dimension ds = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension dw = getSize();
        setLocation((ds.width - dw.width) / 2, (ds.height - dw.height) / 2);
    }
    private void BtPesquisarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtPesquisarProdActionPerformed
        BtAlterar.setEnabled(true);
        BtExcluir.setEnabled(true);
    }//GEN-LAST:event_BtPesquisarProdActionPerformed

    private void BtSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSalvarActionPerformed
        if(TxDescreveProduto.getText().equals("") ||  TxPrecoProd.getText().equals("") || TxPrecoProdVenda.getText().equals("") || TxQtdProd.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Por favor preencha todos os campos");
        }
        else{
            produto = new CadastroProduto();
            produto.setDescriprod(TxDescreveProduto.getText());
            produto.setQtdprod(Integer.valueOf(TxQtdProd.getText()));
            produto.setPrecopag(Float.valueOf(TxPrecoProd.getText()));
            produto.setPrecovenda(Float.valueOf(TxPrecoProdVenda.getText()));
           
            try {
                
                 pt.salvar(produto);
                 JOptionPane.showMessageDialog(null,"Cadastro de produto realizado com susseso!");
                 limpaTabela();
                 Show_Clientes();
                 limpar();
            } catch (SQLException ex) {
                Logger.getLogger(TelaPeças.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
        }
    }//GEN-LAST:event_BtSalvarActionPerformed

    private void BtNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtNovoActionPerformed
        BtSalvar.setEnabled(true);
        TxDescreveProduto.setEditable(true);
        TxPrecoProd.setEditable(true);
        TxPrecoProdVenda.setEditable(true);
        TxQtdProd.setEditable(true);
        
    }//GEN-LAST:event_BtNovoActionPerformed
public void limpar(){
    TxDescreveProduto.setText("");
    TxPrecoProd.setText("");
    TxPrecoProdVenda.setText("");
    TxQtdProd.setText("");
    TxDescreveProduto.setEnabled(false);
    TxPrecoProd.setEnabled(false);
    TxPrecoProdVenda.setEnabled(false);
    TxQtdProd.setEnabled(false);
    BtNovo.setEnabled(true);
    BtSalvar.setEnabled(false);
    BtAlterar.setEnabled(false);
   
            
}
  public ArrayList<CadastroProduto>getLista(){
        ArrayList<CadastroProduto>Lista = new ArrayList<CadastroProduto>();
         Conexao con = new Conexao();
        String sql;
       PreparedStatement pst;
         sql="select *from Produto ";
      
        
        try{
            
         pst=Conexao.getInstance().prepareStatement(sql);
         ResultSet rs= pst.executeQuery();
         CadastroProduto cadc;
            while(rs.next()){
                cadc= new  CadastroProduto(rs.getInt("idproduto") , rs.getString("descricao") , 
                rs.getInt("qtdprod") ,rs.getFloat("precopag")
               ,rs.getFloat("precovenda"));

               
                Lista.add(cadc);
               
            }
        }catch(Exception e){
              e.printStackTrace();
              
        }
        return Lista;
    }
  
   public void Show_Clientes(){
        ArrayList<CadastroProduto>list = getLista();
        DefaultTableModel model = (DefaultTableModel)tblCliente.getModel();
        Object[]row= new Object[4];
        for(int i=0; i < list.size();i++){
            row[0]=list.get(i).getCodproduto();
            row[1]=list.get(i).getDescriprod();
            row[2]=list.get(i).getQtdprod();
            row[3]=list.get(i).getPrecovenda();
            model.addRow(row);
           
        }
      tblCliente.getTableHeader().setReorderingAllowed(false);
   
      
        }
      public void limpaTabela(){
        DefaultTableModel model =(DefaultTableModel)tblCliente.getModel();
        model.setNumRows(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtAlterar;
    private javax.swing.JButton BtExcluir;
    private javax.swing.JButton BtNovo;
    private javax.swing.JButton BtPesquisarProd;
    private javax.swing.JButton BtSalvar;
    private javax.swing.JTextField TxCodProduto;
    private javax.swing.JTextField TxDescreveProduto;
    private javax.swing.JTextField TxPrecoProd;
    private javax.swing.JTextField TxPrecoProdVenda;
    private javax.swing.JTextField TxQtdProd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblCliente;
    // End of variables declaration//GEN-END:variables
}
