/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;


import Dao.Conexao;
import Dao.FuncionarioDao;
import Model.CadastroCliente;
import Model.CadastroUsuário;
import com.lowagie.text.Document;
import com.lowagie.text.DocumentException;
import com.lowagie.text.Element;
import com.lowagie.text.Font;
import com.lowagie.text.PageSize;
import com.lowagie.text.Paragraph;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.List;

public class TelaFuncionario extends javax.swing.JInternalFrame {
   CadastroUsuário cad;
   FuncionarioDao Dao_cad;
   List<FuncionarioDao>listaCliente;
   Document doc;
    /**
     * Creates new form CadastroFuncionario
     */
    public TelaFuncionario() {
        
        cad = new CadastroUsuário();
        Dao_cad = new FuncionarioDao();
        listaCliente= new ArrayList();
        initComponents();
        Show_Clientes();
        BtSalvarF.setEnabled(false);
        BtAlterarF.setEnabled(false);
        TipodeViaF.setEnabled(false);
        TxEstadoF.setEnabled(false);
        
        BtLimparF.setEnabled(false);
        centralizarComponente();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        BtPesquisarConsultaF = new javax.swing.JButton();
        BtLimparF = new javax.swing.JButton();
        BtRelatori = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCliente = new javax.swing.JTable();
        jLabel32 = new javax.swing.JLabel();
        TxConsultaF = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        TxNomeConsultaF = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        TxCepF = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        TipodeViaF = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        TxEndereçoF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TxComplementoF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TxBairroF = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TxTelF = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        TxCelF = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        TxEmailF = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        TxCidadeF = new javax.swing.JTextField();
        TxEstadoF = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        TxUsu = new javax.swing.JTextField();
        TxFunc = new javax.swing.JComboBox<>();
        TxSen = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        TxIdF = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        TxNomeF = new javax.swing.JTextField();
        BtIncluirF = new javax.swing.JButton();
        BtSalvarF = new javax.swing.JButton();
        BtAlterarF = new javax.swing.JButton();
        BtEditar = new javax.swing.JButton();
        BtExcluir = new javax.swing.JButton();
        BtCancelar = new javax.swing.JButton();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("jRadioButtonMenuItem2");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Manutenção");

        BtPesquisarConsultaF.setText("Pesquisar");
        BtPesquisarConsultaF.setEnabled(false);
        BtPesquisarConsultaF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtPesquisarConsultaFActionPerformed(evt);
            }
        });

        BtLimparF.setText("Limpar");
        BtLimparF.setEnabled(false);
        BtLimparF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtLimparFActionPerformed(evt);
            }
        });

        BtRelatori.setText("Relatorio");
        BtRelatori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtRelatoriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtPesquisarConsultaF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtLimparF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtRelatori, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(63, 63, 63))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtPesquisarConsultaF)
                .addGap(19, 19, 19)
                .addComponent(BtLimparF)
                .addGap(18, 18, 18)
                .addComponent(BtRelatori)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblCliente = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex,int colIndex){
                return false;
            }

        };
        tblCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "Endereco", "Bairro"
            }
        ));
        tblCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClienteMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblCliente);

        jLabel32.setText("Cód Funcionário");

        TxConsultaF.setEditable(false);

        jLabel33.setText("Nome");

        TxNomeConsultaF.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32)
                    .addComponent(jLabel33)
                    .addComponent(TxNomeConsultaF, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxConsultaF, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(125, 125, 125)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(87, 87, 87))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxConsultaF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxNomeConsultaF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );

        jTabbedPane1.addTab("Consulta", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTabbedPane2AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("CEP");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        TxCepF.setEditable(false);
        try {
            TxCepF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel6.add(TxCepF, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 31, 88, -1));

        jLabel4.setText("Tipo de Via");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 11, -1, -1));

        TipodeViaF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Avenida", "Rua", "Fazenda" }));
        TipodeViaF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipodeViaFActionPerformed(evt);
            }
        });
        jPanel6.add(TipodeViaF, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 31, -1, -1));

        jLabel6.setText("Endereço");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 11, -1, -1));

        TxEndereçoF.setEditable(false);
        jPanel6.add(TxEndereçoF, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 31, 320, -1));

        jLabel7.setText("Complemento");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 62, -1, -1));

        TxComplementoF.setEditable(false);
        jPanel6.add(TxComplementoF, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 82, 235, -1));

        jLabel8.setText("Bairro");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 62, -1, -1));

        TxBairroF.setEditable(false);
        TxBairroF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxBairroFActionPerformed(evt);
            }
        });
        jPanel6.add(TxBairroF, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 82, 320, -1));

        jLabel9.setText("Telefone Fixo");
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 164, -1, -1));

        TxTelF.setEditable(false);
        try {
            TxTelF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel6.add(TxTelF, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 184, 135, -1));

        jLabel10.setText("Telefone Celular");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 164, -1, -1));

        TxCelF.setEditable(false);
        try {
            TxCelF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel6.add(TxCelF, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 184, 145, -1));

        jLabel11.setText("Email");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 164, -1, -1));

        TxEmailF.setEditable(false);
        jPanel6.add(TxEmailF, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 184, 281, -1));

        jLabel29.setText("Cidade");
        jPanel6.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 113, -1, -1));

        jLabel30.setText("UF");
        jPanel6.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 113, -1, -1));

        TxCidadeF.setEditable(false);
        jPanel6.add(TxCidadeF, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 133, 332, -1));

        TxEstadoF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        jPanel6.add(TxEstadoF, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 133, -1, -1));

        jLabel13.setText("Função");
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 222, -1, -1));

        jLabel14.setText("Usuário");
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 222, -1, -1));

        jLabel31.setText("Senha");
        jPanel6.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 222, -1, -1));

        TxUsu.setEditable(false);
        jPanel6.add(TxUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 242, 170, -1));

        TxFunc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Adiministrador", "Vendedor", "Atendente" }));
        jPanel6.add(TxFunc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 242, 176, -1));
        jPanel6.add(TxSen, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 180, -1));

        jTabbedPane2.addTab("Contato", jPanel6);

        jLabel2.setText("Cód Func");

        TxIdF.setEditable(false);

        jLabel12.setText("Nome");

        TxNomeF.setEditable(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(TxIdF, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(TxNomeF, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel12))
                .addGap(17, 17, 17)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxIdF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxNomeF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 7, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, 410));

        BtIncluirF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icons8-add-48.png"))); // NOI18N
        BtIncluirF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtIncluirFActionPerformed(evt);
            }
        });
        jPanel2.add(BtIncluirF, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 60, 50));

        BtSalvarF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icons8-save-close-48.png"))); // NOI18N
        BtSalvarF.setToolTipText("");
        BtSalvarF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSalvarFActionPerformed(evt);
            }
        });
        jPanel2.add(BtSalvarF, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, 60, 50));

        BtAlterarF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icons8-update-48.png"))); // NOI18N
        BtAlterarF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAlterarFActionPerformed(evt);
            }
        });
        jPanel2.add(BtAlterarF, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, 60, 50));

        BtEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icons8-edit-file-48 (1).png"))); // NOI18N
        BtEditar.setEnabled(false);
        BtEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtEditarActionPerformed(evt);
            }
        });
        jPanel2.add(BtEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, 60, 50));

        BtExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icons8-delete-bin-48.png"))); // NOI18N
        BtExcluir.setEnabled(false);
        BtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtExcluirActionPerformed(evt);
            }
        });
        jPanel2.add(BtExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 440, 60, 50));

        BtCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icons8-delete-48.png"))); // NOI18N
        BtCancelar.setEnabled(false);
        BtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(BtCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 440, 50, 50));

        jTabbedPane1.addTab("Manutenção", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 661, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtIncluirFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtIncluirFActionPerformed
        BtIncluirF.setEnabled(false);
        BtCancelar.setEnabled(true);
        BtExcluir.setEnabled(false);
        BtEditar.setEnabled(false);
        TxIdF.setText("");
        TxNomeF.setText("");
        TxEndereçoF.setText("");
        TxComplementoF.setText("");
        TxBairroF.setText("");
        TxCidadeF.setText("");
        TxTelF.setText("");
        TxCelF.setText("");
        TxEmailF.setText("");
        TxCepF.setText("");
        TxEstadoF.setSelectedItem("Selecione");
        TipodeViaF.setSelectedItem("Selecione");
        TxEmailF.setText("");
        TxFunc.setSelectedItem("Selecione");
        TxUsu.setText("");
        TxSen.setText("");
        TxCepF.setText("");
        TxNomeF.setEditable(true);
        TxEndereçoF.setEditable(true);
        TxComplementoF.setEditable(true);
        TxBairroF.setEditable(true);
        TxTelF.setEditable(true);
        TxCelF.setEditable(true);
        TxEmailF.setEditable(true);
        TxEstadoF.setEnabled(true);
        TipodeViaF.setEnabled(true);
        TxCidadeF.setEditable(true);
        TxCepF.setEditable(true);
        TxFunc.setEditable(true);
        TxUsu.setEditable(true);
        TxSen.setEditable(true);

        BtSalvarF.setEnabled(true);

    }//GEN-LAST:event_BtIncluirFActionPerformed

    private void BtSalvarFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSalvarFActionPerformed
        if(TxNomeF.getText().length()== 0 || TxFunc.getSelectedItem().equals("Selecione") || TxUsu.getText().length()==0 
              || TxSen.getText().length()==0 || TxComplementoF.getText().length()==0 || TxCidadeF.getText().length()==0
                ||TxEndereçoF.getText().length()==0 || TxBairroF.getText().length()==0 || TxTelF.getText().equals("(  )    -    ") || TxCelF.getText().equals("(  )    -    ") || TxEmailF.getText().length()==0 
                || TipodeViaF.getSelectedItem().equals("Selecione") || TxEstadoF.getSelectedItem().equals("Selecione") || TxCepF.getText().equals("     -   "))
        {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
        }
        else{
            cad = new CadastroUsuário();
            cad.setNome(TxNomeF.getText());
            cad.setFunção(String.valueOf(TxFunc.getSelectedItem()));
            cad.setUsuario(TxUsu.getText());
            cad.setSenha(TxSen.getText());
            cad.setComplemento(TxComplementoF.getText());
            cad.setCidade(TxCidadeF.getText());
            cad.setEndereço(TxEndereçoF.getText());
            cad.setBairro(TxBairroF.getText());
            cad.setTelefone(TxTelF.getText().replace("(","").replace(")","").replace("-",""));
            cad.setCelular(TxCelF.getText().replace("(","").replace(")","").replace("-",""));
            cad.setEmail(TxEmailF.getText());
            cad.setTipodevia(String.valueOf(TipodeViaF.getSelectedItem()));
            cad.setEstado(String.valueOf(TxEstadoF.getSelectedItem()));
            cad.setCep(TxCepF.getText().replace("-",""));
            limpar();
            try {
                JOptionPane.showMessageDialog(null,"Cadastro realizado com sucesso!");
                Dao_cad.salvar(cad);
                limpaTabela();
                Show_Clientes();
                BtIncluirF.setEnabled(true);
            } catch (SQLException ex) {
                Logger.getLogger(TelaFuncionario.class.getName()).log(Level.SEVERE, null, ex);
            }
           
            
         }
    }//GEN-LAST:event_BtSalvarFActionPerformed
public void limpar(){
                BtIncluirF.setEnabled(true);
                BtCancelar.setEnabled(false);
                TxIdF.setText("");
                TxNomeF.setText("");
                TxEndereçoF.setText("");
                TxComplementoF.setText("");
                TxBairroF.setText("");
                TxCidadeF.setText("");
                TxTelF.setText("");
                TxCelF.setText("");
                TxEmailF.setText("");
                TxCepF.setText("");
                TxEstadoF.setSelectedItem("Selecione");
                TipodeViaF.setSelectedItem("Selecione");
                TxEmailF.setText("");
                TxFunc.setSelectedItem("Selecione");
                TxUsu.setText("");
                TxSen.setText("");
                TxCepF.setText("");
                TxNomeF.setEditable(false);
                TxEndereçoF.setEditable(false);
                TxComplementoF.setEditable(false);
                TxBairroF.setEditable(false);
                TxTelF.setEditable(false);
                TxCelF.setEditable(false);
                TxEmailF.setEditable(false);
                TxEstadoF.setEnabled(false);
                TipodeViaF.setEnabled(false);
                TxCidadeF.setEditable(false);
                TxCepF.setEditable(false);
                TxUsu.setEditable(false);
                TxFunc.setEditable(false);
                TxSen.setEditable(false);
                BtSalvarF.setEnabled(false);
                BtExcluir.setEnabled(false);
                BtAlterarF.setEnabled(false);
                BtEditar.setEnabled(false);
               
    
}
    private void BtAlterarFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAlterarFActionPerformed
    
        
        int op = JOptionPane.showConfirmDialog(this, "Deseja realmente alterar?", "Confirmação",JOptionPane.YES_NO_OPTION);
        if(op==0){
        
        
        
        if(TxNomeF.getText().length()== 0 || TxFunc.getSelectedItem().equals("Selecione") || TxUsu.getText().length()==0 
              || TxSen.getText().length()==0 || TxComplementoF.getText().length()==0 || TxCidadeF.getText().length()==0
                ||TxEndereçoF.getText().length()==0 || TxBairroF.getText().length()==0 || TxTelF.getText().equals("(  )    -    ") || TxCelF.getText().equals("(  )    -    ") || TxEmailF.getText().length()==0 
                || TipodeViaF.getSelectedItem().equals("Selecione") || TxEstadoF.getSelectedItem().equals("Selecione") || TxCepF.getText().equals("     -   "))
        {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
        }
         
        else{
         
            cad.setId(Integer.valueOf(TxIdF.getText()));
            cad.setNome(TxNomeF.getText());
            cad.setFunção(String.valueOf(TxFunc.getSelectedItem()));
            cad.setUsuario(TxUsu.getText());
            cad.setSenha(TxSen.getText());
            cad.setComplemento(TxComplementoF.getText());
            cad.setCidade(TxCidadeF.getText());
            cad.setEndereço(TxEndereçoF.getText());
            cad.setBairro(TxBairroF.getText());
            cad.setTelefone(TxTelF.getText().replace("(","").replace(")","").replace("-",""));
            cad.setCelular(TxCelF.getText().replace("(","").replace(")","").replace("-",""));
            cad.setEmail(TxEmailF.getText());
            cad.setTipodevia(String.valueOf(TipodeViaF.getSelectedItem()));
            cad.setEstado(String.valueOf(TxEstadoF.getSelectedItem()));
            cad.setCep(TxCepF.getText().replace("-",""));
            try {
                Dao_cad.Alterar(cad);
                 JOptionPane.showMessageDialog(null,"Funcionario Alterado com sucesso!");
                   limpar();
                   limpaTabela();
                   Show_Clientes();
            } catch (SQLException ex) {
                Logger.getLogger(TelaFuncionario.class.getName()).log(Level.SEVERE, null, ex);
            }
           
            
         }
        
        
        }
       
    }//GEN-LAST:event_BtAlterarFActionPerformed

    private void BtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtExcluirActionPerformed
     
        
        int op = JOptionPane.showConfirmDialog(this, "Deseja realmente Excluir?", "Confirmação",JOptionPane.YES_NO_OPTION);
        if(op==0){
        cad.setId(Integer.valueOf(TxIdF.getText()));
       try {
           Dao_cad.Excluir(cad);
           limpar();
           limpaTabela();
           Show_Clientes();
           BtEditar.setEnabled(false);
       } catch (SQLException ex) {
           Logger.getLogger(TelaFuncionario.class.getName()).log(Level.SEVERE, null, ex);
       }
        }
    }//GEN-LAST:event_BtExcluirActionPerformed

    private void jTabbedPane2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTabbedPane2AncestorAdded

    }//GEN-LAST:event_jTabbedPane2AncestorAdded

    private void TxBairroFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxBairroFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxBairroFActionPerformed

    private void TipodeViaFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipodeViaFActionPerformed

    }//GEN-LAST:event_TipodeViaFActionPerformed

    private void BtPesquisarConsultaFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtPesquisarConsultaFActionPerformed
        if (TxConsultaF.getText().isEmpty() && TxNomeConsultaF.getText().isEmpty()) {
            
            JOptionPane.showMessageDialog(null, "Digite algum parâmetro para a pesquisa!");
        } else {
            BtLimparF.setEnabled(true);
        }
    }//GEN-LAST:event_BtPesquisarConsultaFActionPerformed

    private void BtLimparFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtLimparFActionPerformed
        int op = JOptionPane.showConfirmDialog(this, "Deseja realmente limpar?", "Confirmação",JOptionPane.YES_NO_OPTION);

        if(op==0){
            TxConsultaF.setText("");
            TxNomeConsultaF.setText("");
            }
        BtLimparF.setEnabled(false);
    }//GEN-LAST:event_BtLimparFActionPerformed

    private void BtRelatoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtRelatoriActionPerformed
    
          String nomediretorio = null;
        String nomepasta = "SRS"; // Informe o nome da pasta que armazenará o relatório
        String separador = java.io.File.separator;
        try {
            nomediretorio = "C:" + separador + nomepasta;
            if (!new File(nomediretorio).exists()) {
                (new File(nomediretorio)).mkdir();
            }
            gerarDocumento();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_BtRelatoriActionPerformed

    private void tblClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClienteMouseClicked
        BtIncluirF.setEnabled(false);
        BtCancelar.setEnabled(true);
        TxNomeF.setEditable(false);
        BtSalvarF.setEnabled(false);
        TxEndereçoF.setEditable(false);
        TxComplementoF.setEditable(false);
        TxBairroF.setEditable(false);
        TxTelF.setEditable(false);
        TxCelF.setEditable(false);
        TxEmailF.setEditable(false);
        TxEstadoF.setEnabled(false);
        TipodeViaF.setEnabled(false);
        TxCidadeF.setEditable(false);
        TxCepF.setEditable(false);
        TxUsu.setEditable(false);
        TxFunc.setEditable(false);
        TxSen.setEditable(false);
        BtExcluir.setEnabled(true);
        BtEditar.setEnabled(true);
        BtAlterarF.setEnabled(false);
        String id =""+tblCliente.getValueAt(tblCliente.getSelectedRow(),0);
       Conexao con = new Conexao();
       String sql;
       PreparedStatement pst;
       sql="select *from Funcionario where idFuncionario= "+id;
       try {
        pst=Conexao.getInstance().prepareStatement(sql);
        ResultSet rs= pst.executeQuery();
      while(rs.next()){
          TxIdF.setText(String.valueOf(rs.getInt("idFuncionario")));
          TxNomeF.setText(rs.getString("nome"));
          TxEndereçoF.setText(rs.getString("endereco"));
          TxComplementoF.setText(rs.getString("complemento"));
          TxBairroF.setText(rs.getString("bairro"));
          TxCidadeF.setText(rs.getString("cidade"));
          TxTelF.setText(rs.getString("telefone"));
          TxCelF.setText(rs.getString("celular"));
          TxEmailF.setText(rs.getString("email"));
          TipodeViaF.setSelectedItem(rs.getString("tipodevia"));
          TxEstadoF.setSelectedItem((rs.getString("estado")));
          TxCepF.setText(rs.getString("cep"));
          TxUsu.setText(rs.getString("usuario"));
          TxSen.setText(rs.getString("senha"));
          TxFunc.setSelectedItem(rs.getString("funcao"));
        
          
          
      }
       } catch (SQLException ex) {
           Logger.getLogger(TelaCliente.class.getName()).log(Level.SEVERE, null, ex);
       }
    
    }//GEN-LAST:event_tblClienteMouseClicked

    private void BtEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtEditarActionPerformed
               BtAlterarF.setEnabled(true);
                TxNomeF.setEditable(true);
                TxEndereçoF.setEditable(true);
                TxComplementoF.setEditable(true);
                TxBairroF.setEditable(true);
                TxTelF.setEditable(true);
                TxCelF.setEditable(true);
                TxEmailF.setEditable(true);
                TxEstadoF.setEnabled(true);
                TipodeViaF.setEnabled(true);
                TxCidadeF.setEditable(true);
                TxCepF.setEditable(true);
                TxUsu.setEditable(true);
                TxFunc.setEditable(true);
                TxSen.setEditable(true);
                TxNomeF.setEnabled(true);
                TxEndereçoF.setEnabled(true);
                TxComplementoF.setEnabled(true);
                TxBairroF.setEnabled(true);
                TxTelF.setEnabled(true);
                TxCelF.setEnabled(true);
                TxEmailF.setEnabled(true);
                TxEstadoF.setEnabled(true);
                TipodeViaF.setEnabled(true);
                TxCidadeF.setEnabled(true);
                TxCepF.setEnabled(true);
                TxUsu.setEnabled(true);
                TxFunc.setEnabled(true);
                TxSen.setEnabled(true);
                BtEditar.setEnabled(false);
                BtExcluir.setEnabled(false);
    }//GEN-LAST:event_BtEditarActionPerformed

    private void BtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCancelarActionPerformed
      limpar();
    }//GEN-LAST:event_BtCancelarActionPerformed

    public void centralizarComponente() {
        Dimension ds = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension dw = getSize();
        setLocation((ds.width - dw.width) / 2, (ds.height - dw.height) / 2);
    }
          
   /* public void atualizarTabela(){
    cad= new CadastroUsuário();
    try{
      listaCliente=Dao_cad.ListaCliente();
        
    }catch(SQLException ex){
        
    }
    String dados[][]= new String[listaCliente.size()][4]; 
            int i = 0;
            for(CadastroUsuário cliente:listaCliente){
                dados[i][0]=String.valueOf(cliente.getId());
                dados[i][1]=(cliente.getNome());
                dados[i][2]=(cliente.getEndereço());
                dados[i][3]=(cliente.getBairro());
            }
            String tituloColuna[]={"Codigo","Nome","Endereço","Bairro"};
            DefaultTableModel tabelaCliente = new DefaultTableModel();
            tabelaCliente.setDataVector(dados,tituloColuna);
            tblCliente.setModel(new DefaultTableModel(dados,tituloColuna){
            boolean[] canEdit= new boolean[]{
            false,false,false,false
         }; 
         public boolean isCellEditable(int rowindex,int columnIndex){
                return canEdit[columnIndex];
            };
         
            
         
   });
            tblCliente.getColumnModel().getColumn(0).setPreferredWidth(100);
            tblCliente.getColumnModel().getColumn(0).setPreferredWidth(300);
            tblCliente.getColumnModel().getColumn(0).setPreferredWidth(150);
            tblCliente.getColumnModel().getColumn(0).setPreferredWidth(200);
            
            DefaultTableCellRenderer centralisado= new DefaultTableCellRenderer();
            centralisado.setHorizontalAlignment(SwingConstants.CENTER);
            tblCliente.getColumnModel().getColumn(0).setCellRenderer(centralisado);
            tblCliente.setRowHeight(25);
            tblCliente.updateUI();
            
            
      
   }*/
     public ArrayList<CadastroUsuário>getLista(){
        ArrayList<CadastroUsuário>Lista = new ArrayList<CadastroUsuário>();
         Conexao con = new Conexao();
        String sql;
       PreparedStatement pst;
         sql="select *from Funcionario ";
      
        
        try{
            
         pst=Conexao.getInstance().prepareStatement(sql);
         ResultSet rs= pst.executeQuery();
         CadastroUsuário cadc;
            while(rs.next()){
                cadc= new  CadastroUsuário(rs.getInt("idFuncionario") , rs.getString("nome") , 
                rs.getString("endereco") ,rs.getString("complemento")
               ,rs.getString("bairro"),rs.getString("cidade"),
                rs.getString("telefone"),rs.getString("celular"),
                rs.getString("email"),rs.getString("funcao")
               ,rs.getString("usuario"),rs.getString("senha"),rs.getString("tipodevia")
               ,rs.getString("estado"),rs.getString("cep"));
              
                Lista.add(cadc);
               
            }
        }catch(Exception e){
              e.printStackTrace();
              
        }
        return Lista;
    }
       public void Show_Clientes(){
        ArrayList<CadastroUsuário>list = getLista();
        DefaultTableModel model = (DefaultTableModel)tblCliente.getModel();
        Object[]row= new Object[4];
        for(int i=0; i < list.size();i++){
            row[0]=list.get(i).getId();
            row[1]=list.get(i).getNome();
            row[2]=list.get(i).getEndereço();
            row[3]=list.get(i).getBairro();
            model.addRow(row);
           
        }
      tblCliente.getTableHeader().setReorderingAllowed(false);
   
      
        }
      public void limpaTabela(){
        DefaultTableModel model =(DefaultTableModel)tblCliente.getModel();
        model.setNumRows(0);
    }
      public void gerarDocumento(){
           try {
       ArrayList<CadastroUsuário>list = getLista();
            
            doc = new Document(PageSize.A4, 41.5f, 41.5f, 55.2f, 55.2f);
            PdfWriter.getInstance(doc, new FileOutputStream("C:/SRS/RelatorioFuncionario" + ".pdf"));
            doc.open();

            Font f1 = new Font(Font.HELVETICA, 14, Font.BOLD);
            Font f2 = new Font(Font.HELVETICA, 12, Font.BOLD);
            Font f3 = new Font(Font.HELVETICA, 12, Font.NORMAL);
            Font f4 = new Font(Font.HELVETICA, 10, Font.BOLD);
            Font f5 = new Font(Font.HELVETICA, 10, Font.NORMAL);

            Paragraph titulo1 = new Paragraph("Universidade do Estado de Minas Gerais", f2);
            titulo1.setAlignment(Element.ALIGN_CENTER);
            titulo1.setSpacingAfter(10);

            Paragraph titulo2 = new Paragraph("Relatório de Funcionarios", f1);
            titulo2.setAlignment(Element.ALIGN_CENTER);
            titulo2.setSpacingAfter(0);

            PdfPTable tabela = new PdfPTable(new float[]{0.40f, 0.60f});
            tabela.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabela.setWidthPercentage(100f);

            PdfPCell cabecalho1 = new PdfPCell(new Paragraph("Nome", f3));
            //cabecalho1.setBackgroundColor(new Color(0xc0, 0xc0, 0xc0));
            cabecalho1.setHorizontalAlignment(Element.ALIGN_JUSTIFIED);
            cabecalho1.setBorder(0);

            PdfPCell cabecalho2 = new PdfPCell(new Paragraph("Endereço", f3));
            //cabecalho2.setBackgroundColor(new Color(0xc0, 0xc0, 0xc0));
            cabecalho2.setHorizontalAlignment(Element.ALIGN_JUSTIFIED);
            cabecalho2.setBorder(0);

            tabela.addCell(cabecalho1);
            tabela.addCell(cabecalho2);
            for (int i=0; i < list.size();i++) {
                Paragraph p1 = new Paragraph(list.get(i).getNome(), f5);
                p1.setAlignment(Element.ALIGN_JUSTIFIED);
                PdfPCell col1 = new PdfPCell(p1);
                col1.setBorder(0);
                
                Paragraph p2 = new Paragraph(list.get(i).getEndereço(), f5);
                p2.setAlignment(Element.ALIGN_JUSTIFIED);
                PdfPCell col2 = new PdfPCell(p2);
                col2.setBorder(0);
                tabela.addCell(col1);
                tabela.addCell(col2);
            }
            
            doc.add(titulo2);
            doc.add(titulo1);
            doc.add(tabela);
            doc.close();
            
            JOptionPane.showMessageDialog(null, "Relatório salvo com sucesso");
            String caminho = "C:/SRS/RelatorioFuncionario.pdf";
            Desktop.getDesktop().open(new File(caminho));
        } catch (DocumentException e) {
            e.printStackTrace();
        } catch (IOException exx) {
            exx.printStackTrace();
            JOptionPane.showMessageDialog(null, "Documento de Requisitos aberto. Feche para gerar um novo.");
        }

          
      }
       

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtAlterarF;
    private javax.swing.JButton BtCancelar;
    private javax.swing.JButton BtEditar;
    private javax.swing.JButton BtExcluir;
    private javax.swing.JButton BtIncluirF;
    private javax.swing.JButton BtLimparF;
    private javax.swing.JButton BtPesquisarConsultaF;
    private javax.swing.JButton BtRelatori;
    private javax.swing.JButton BtSalvarF;
    private javax.swing.JComboBox<String> TipodeViaF;
    private javax.swing.JTextField TxBairroF;
    private javax.swing.JFormattedTextField TxCelF;
    private javax.swing.JFormattedTextField TxCepF;
    private javax.swing.JTextField TxCidadeF;
    private javax.swing.JTextField TxComplementoF;
    private javax.swing.JTextField TxConsultaF;
    private javax.swing.JTextField TxEmailF;
    private javax.swing.JTextField TxEndereçoF;
    private javax.swing.JComboBox<String> TxEstadoF;
    private javax.swing.JComboBox<String> TxFunc;
    private javax.swing.JTextField TxIdF;
    private javax.swing.JTextField TxNomeConsultaF;
    private javax.swing.JTextField TxNomeF;
    private javax.swing.JPasswordField TxSen;
    private javax.swing.JFormattedTextField TxTelF;
    private javax.swing.JTextField TxUsu;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblCliente;
    // End of variables declaration//GEN-END:variables
}
