/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import Dao.Conexao;
import Dao.ProdutoDao;
import Model.CadastroProduto;
import Model.CadastroUsuário;
import com.lowagie.text.Document;
import com.lowagie.text.DocumentException;
import com.lowagie.text.Element;
import com.lowagie.text.Font;
import com.lowagie.text.PageSize;
import com.lowagie.text.Paragraph;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gabriel
 */
public class TelaPeças extends javax.swing.JInternalFrame {
  CadastroProduto produto;
  ProdutoDao pt;
  Document doc;
    public TelaPeças() {
        pt = new ProdutoDao();
        produto= new CadastroProduto();
        initComponents();
        Show_Clientes();
        centralizarComponente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TxCodProduto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TxDescreveProduto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TxQtdProd = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TxPrecoProd = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TxPrecoProdVenda = new javax.swing.JTextField();
        BtNovo = new javax.swing.JButton();
        BtSalvar = new javax.swing.JButton();
        BtAlterar = new javax.swing.JButton();
        BtExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCliente = new javax.swing.JTable();
        BtEditar = new javax.swing.JButton();
        BtRelatorio = new javax.swing.JButton();
        BtCancelar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Cadastro de Produto");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Cod:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        TxCodProduto.setEditable(false);
        jPanel1.add(TxCodProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 32, 60, -1));

        jLabel2.setText("Descriçao do Produto:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 11, -1, -1));

        TxDescreveProduto.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TxDescreveProdutoCaretUpdate(evt);
            }
        });
        jPanel1.add(TxDescreveProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 32, 469, -1));

        jLabel3.setText("Quantidade:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 72, -1, -1));

        TxQtdProd.setEditable(false);
        jPanel1.add(TxQtdProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 93, 60, -1));

        jLabel4.setText("Preço Pago:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 72, -1, -1));

        TxPrecoProd.setEditable(false);
        jPanel1.add(TxPrecoProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 93, 73, -1));

        jLabel5.setText("Preço Venda Unitario:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 72, -1, -1));

        TxPrecoProdVenda.setEditable(false);
        jPanel1.add(TxPrecoProdVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 93, 73, -1));

        BtNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icons8-add-48.png"))); // NOI18N
        BtNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtNovoActionPerformed(evt);
            }
        });
        jPanel1.add(BtNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 138, 68, 49));

        BtSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icons8-save-close-48.png"))); // NOI18N
        BtSalvar.setEnabled(false);
        BtSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(BtSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 138, 68, 49));

        BtAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icons8-update-48.png"))); // NOI18N
        BtAlterar.setEnabled(false);
        BtAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAlterarActionPerformed(evt);
            }
        });
        jPanel1.add(BtAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 138, 68, 49));

        BtExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icons8-delete-bin-48.png"))); // NOI18N
        BtExcluir.setEnabled(false);
        BtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(BtExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 68, 49));

        tblCliente = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex,int colIndex){
                return false;
            }

        };
        tblCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "descricao", "Quantidade", "Preço Venda"
            }
        ));
        tblCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCliente);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 206, 671, 297));

        BtEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icons8-edit-file-48 (1).png"))); // NOI18N
        BtEditar.setEnabled(false);
        BtEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtEditarMouseClicked(evt);
            }
        });
        BtEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtEditarActionPerformed(evt);
            }
        });
        jPanel1.add(BtEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 68, 49));

        BtRelatorio.setText("Relatorio");
        BtRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtRelatorioActionPerformed(evt);
            }
        });
        jPanel1.add(BtRelatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 92, -1, -1));

        BtCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icons8-delete-48.png"))); // NOI18N
        BtCancelar.setEnabled(false);
        BtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(BtCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 68, 49));

        jTabbedPane1.addTab("Cadastro", jPanel1);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 533));
        jTabbedPane1.getAccessibleContext().setAccessibleName("Cadastro");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void centralizarComponente() {
        Dimension ds = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension dw = getSize();
        setLocation((ds.width - dw.width) / 2, (ds.height - dw.height) / 2);
    }
    private void BtSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSalvarActionPerformed
        if(TxDescreveProduto.getText().equals("") ||  TxPrecoProd.getText().equals("") || TxPrecoProdVenda.getText().equals("") || TxQtdProd.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Por favor preencha todos os campos");
        }
        else{
            produto = new CadastroProduto();
            produto.setDescriprod(TxDescreveProduto.getText());
            produto.setQtdprod(Integer.valueOf(TxQtdProd.getText()));
            produto.setPrecopag(Float.valueOf(TxPrecoProd.getText().replace(",",".")));
            produto.setPrecovenda(Float.valueOf(TxPrecoProdVenda.getText().replace(",",".")));
           
            try {
                
                 pt.salvar(produto);
                 JOptionPane.showMessageDialog(null,"Cadastro de produto realizado com susseso!");
                 limpaTabela();
                 Show_Clientes();
                 limpar();
                 TxDescreveProduto.setEnabled(true);
       TxDescreveProduto.setEditable(true);
            } catch (SQLException ex) {
                Logger.getLogger(TelaPeças.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
        }
    }//GEN-LAST:event_BtSalvarActionPerformed

    private void BtNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtNovoActionPerformed
        TxCodProduto.setText("");
        TxDescreveProduto.setText("");
        TxPrecoProd.setText("");
        TxPrecoProdVenda.setText("");
        TxQtdProd.setText("");
        BtSalvar.setEnabled(true);
        TxDescreveProduto.setEditable(true);
        TxPrecoProd.setEditable(true);
        TxPrecoProdVenda.setEditable(true);
        TxQtdProd.setEditable(true);
        BtEditar.setEnabled(false);
        BtExcluir.setEnabled(false);
        BtNovo.setEnabled(false);
        BtCancelar.setEnabled(true);
        
    }//GEN-LAST:event_BtNovoActionPerformed

    private void tblClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClienteMouseClicked
        BtNovo.setEnabled(false);
        BtCancelar.setEnabled(true);
        BtExcluir.setEnabled(true);
        BtEditar.setEnabled(true);
        BtSalvar.setEnabled(false);
       
        TxDescreveProduto.setEditable(false);
        TxPrecoProd.setEditable(false);
        TxPrecoProdVenda.setEditable(false);
        TxQtdProd.setEditable(false);
        BtAlterar.setEnabled(false);
        String id =""+tblCliente.getValueAt(tblCliente.getSelectedRow(),0);
       Conexao con = new Conexao();
       String sql;
       PreparedStatement pst;
       sql="select *from Produto where idproduto= "+id;
       try {
        pst=Conexao.getInstance().prepareStatement(sql);
        ResultSet rs= pst.executeQuery();
      while(rs.next()){
          TxCodProduto.setText(String.valueOf(rs.getInt("idproduto")));
          TxDescreveProduto.setText(rs.getString("descricao"));
          TxPrecoProd.setText(rs.getString("precopag"));
          TxPrecoProdVenda.setText(rs.getString("precovenda"));
          TxQtdProd.setText(rs.getString("qtdprod"));
          
       
        
          
          
      }
       } catch (SQLException ex) {
           Logger.getLogger(TelaCliente.class.getName()).log(Level.SEVERE, null, ex);
       }
        
    }//GEN-LAST:event_tblClienteMouseClicked

    private void BtEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtEditarMouseClicked
      BtAlterar.setEnabled(true);
      TxDescreveProduto.setEditable(true);
      TxPrecoProd.setEditable(true);
      TxPrecoProdVenda.setEditable(true);
      TxQtdProd.setEditable(true);
    }//GEN-LAST:event_BtEditarMouseClicked

    private void BtAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAlterarActionPerformed
        int op = JOptionPane.showConfirmDialog(this, "Deseja realmente Alterar?", "Confirmação",JOptionPane.YES_NO_OPTION);
        if(op==0){
        if(TxDescreveProduto.getText().equals("") ||  TxPrecoProd.getText().equals("") || TxPrecoProdVenda.getText().equals("") || TxQtdProd.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Por favor preencha todos os campos");
        }
        else{
            produto.setCodproduto(Integer.valueOf(TxCodProduto.getText()));
            produto.setDescriprod(TxDescreveProduto.getText());
            produto.setQtdprod(Integer.valueOf(TxQtdProd.getText()));
            produto.setPrecopag(Float.valueOf(TxPrecoProd.getText().replace(",",".")));
            produto.setPrecovenda(Float.valueOf(TxPrecoProdVenda.getText().replace(",",".")));
           
            try {
                System.out.println(""+produto.getDescriprod());
                 pt.Alterar(produto);
                 JOptionPane.showMessageDialog(null,"Produto Alterado com susseso!");
                 limpaTabela();
                 Show_Clientes();
                 limpar();
                 TxDescreveProduto.setEnabled(true);
       TxDescreveProduto.setEditable(true);
            } catch (SQLException ex) {
                Logger.getLogger(TelaPeças.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
        }
        }
    }//GEN-LAST:event_BtAlterarActionPerformed

    private void BtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtExcluirActionPerformed
     int op = JOptionPane.showConfirmDialog(this, "Deseja realmente Excluir?", "Confirmação",JOptionPane.YES_NO_OPTION);
        if(op==0){
     produto = new CadastroProduto();
     produto.setCodproduto(Integer.valueOf(TxCodProduto.getText()));
      try {
          pt.Excluir(produto);
          BtExcluir.setEnabled(false);
          limpar();
          TxDescreveProduto.setEnabled(true);
       TxDescreveProduto.setEditable(true);
          limpaTabela();
          Show_Clientes();
      } catch (SQLException ex) {
          Logger.getLogger(TelaPeças.class.getName()).log(Level.SEVERE, null, ex);
      }
        }
    }//GEN-LAST:event_BtExcluirActionPerformed

    private void BtEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtEditarActionPerformed
     BtAlterar.setEnabled(true);
     BtExcluir.setEnabled(false);
     BtEditar.setEnabled(false);
    TxDescreveProduto.setEditable(true);
    TxPrecoProd.setEditable(true);
    TxPrecoProdVenda.setEditable(true);
    TxQtdProd.setEditable(true);
     
     
    }//GEN-LAST:event_BtEditarActionPerformed

    private void BtRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtRelatorioActionPerformed
        String nomediretorio = null;
        String nomepasta = "SRS"; // Informe o nome da pasta que armazenará o relatório
        String separador = java.io.File.separator;
        try {
            nomediretorio = "C:" + separador + nomepasta;
            if (!new File(nomediretorio).exists()) {
                (new File(nomediretorio)).mkdir();
            }
            gerarDocumento();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_BtRelatorioActionPerformed

    private void BtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCancelarActionPerformed
       limpar();
       TxDescreveProduto.setEnabled(true);
       TxDescreveProduto.setEditable(true);
    }//GEN-LAST:event_BtCancelarActionPerformed

    private void TxDescreveProdutoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TxDescreveProdutoCaretUpdate
      limpaTabela();
      Show_Clientes();
    }//GEN-LAST:event_TxDescreveProdutoCaretUpdate
public void limpar(){
    TxCodProduto.setText("");
    TxDescreveProduto.setText("");
    TxPrecoProd.setText("");
    TxPrecoProdVenda.setText("");
    TxQtdProd.setText("");
    TxDescreveProduto.setEditable(false);
    TxPrecoProd.setEditable(false);
    TxPrecoProdVenda.setEditable(false);
    TxQtdProd.setEditable(false);
    BtNovo.setEnabled(true);
    BtSalvar.setEnabled(false);
    BtAlterar.setEnabled(false);
    BtEditar.setEnabled(false);
    BtCancelar.setEnabled(false);
    BtExcluir.setEnabled(false);
   
            
}
  public ArrayList<CadastroProduto>getLista(){
        ArrayList<CadastroProduto>Lista = new ArrayList<CadastroProduto>();
         Conexao con = new Conexao();
        String sql;
       PreparedStatement pst;
         sql="select *from Produto ";
      
       if(TxDescreveProduto.getText().isEmpty()){ 
        try{
            
         pst=Conexao.getInstance().prepareStatement(sql);
         ResultSet rs= pst.executeQuery();
         CadastroProduto cadc;
            while(rs.next()){
                cadc= new  CadastroProduto(rs.getInt("idproduto") , rs.getString("descricao") , 
                rs.getInt("qtdprod") ,rs.getFloat("precopag")
               ,rs.getFloat("precovenda"));

               
                Lista.add(cadc);
               
            }
        }catch(Exception e){
              e.printStackTrace();
              
        }
       }else{
             sql="select *from Produto where descricao like '%"+TxDescreveProduto.getText()+"%'"; 
            try {
                pst=Conexao.getInstance().prepareStatement(sql);
                ResultSet rs= pst.executeQuery();
            CadastroProduto cadc;
            while(rs.next()){
                cadc= new  CadastroProduto(rs.getInt("idproduto") , rs.getString("descricao") , 
                rs.getInt("qtdprod") ,rs.getFloat("precopag")
               ,rs.getFloat("precovenda"));

               
                Lista.add(cadc);
               
            }
            
            } catch (SQLException ex) {
                Logger.getLogger(TelaVenda.class.getName()).log(Level.SEVERE, null, ex);
            }
       }
        return Lista;
    }
  
   public void Show_Clientes(){
        ArrayList<CadastroProduto>list = getLista();
        DefaultTableModel model = (DefaultTableModel)tblCliente.getModel();
        Object[]row= new Object[4];
        for(int i=0; i < list.size();i++){
            row[0]=list.get(i).getCodproduto();
            row[1]=list.get(i).getDescriprod();
            row[2]=list.get(i).getQtdprod();
            row[3]=list.get(i).getPrecovenda();
            model.addRow(row);
           
        }
      tblCliente.getTableHeader().setReorderingAllowed(false);
   
      
        }
      public void limpaTabela(){
        DefaultTableModel model =(DefaultTableModel)tblCliente.getModel();
        model.setNumRows(0);
    }
      public void gerarDocumento(){
             try {
       ArrayList<CadastroProduto>list = getLista();
            
            doc = new Document(PageSize.A4, 41.5f, 41.5f, 55.2f, 55.2f);
            PdfWriter.getInstance(doc, new FileOutputStream("C:/SRS/RelatorioProduto" + ".pdf"));
            doc.open();

            Font f1 = new Font(Font.HELVETICA, 14, Font.BOLD);
            Font f2 = new Font(Font.HELVETICA, 12, Font.BOLD);
            Font f3 = new Font(Font.HELVETICA, 12, Font.NORMAL);
            Font f4 = new Font(Font.HELVETICA, 10, Font.BOLD);
            Font f5 = new Font(Font.HELVETICA, 10, Font.NORMAL);

            Paragraph titulo1 = new Paragraph("Universidade do Estado de Minas Gerais", f2);
            titulo1.setAlignment(Element.ALIGN_CENTER);
            titulo1.setSpacingAfter(10);

            Paragraph titulo2 = new Paragraph("Relatório de Produtos", f1);
            titulo2.setAlignment(Element.ALIGN_CENTER);
            titulo2.setSpacingAfter(0);

            PdfPTable tabela = new PdfPTable(new float[]{0.40f, 0.60f});
            tabela.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabela.setWidthPercentage(100f);

            PdfPCell cabecalho1 = new PdfPCell(new Paragraph("Descriçao", f3));
            //cabecalho1.setBackgroundColor(new Color(0xc0, 0xc0, 0xc0));
            cabecalho1.setHorizontalAlignment(Element.ALIGN_JUSTIFIED);
            cabecalho1.setBorder(0);

            PdfPCell cabecalho2 = new PdfPCell(new Paragraph("Quantidade", f3));
            //cabecalho2.setBackgroundColor(new Color(0xc0, 0xc0, 0xc0));
            cabecalho2.setHorizontalAlignment(Element.ALIGN_JUSTIFIED);
            cabecalho2.setBorder(0);

            tabela.addCell(cabecalho1);
            tabela.addCell(cabecalho2);
            for (int i=0; i < list.size();i++) {
                Paragraph p1 = new Paragraph(list.get(i).getDescriprod(), f5);
                p1.setAlignment(Element.ALIGN_JUSTIFIED);
                PdfPCell col1 = new PdfPCell(p1);
                col1.setBorder(0);
                
                Paragraph p2 = new Paragraph(String.valueOf(list.get(i).getQtdprod()), f5);
                p2.setAlignment(Element.ALIGN_JUSTIFIED);
                PdfPCell col2 = new PdfPCell(p2);
                col2.setBorder(0);
                tabela.addCell(col1);
                tabela.addCell(col2);
            }
            
            doc.add(titulo2);
            doc.add(titulo1);
            doc.add(tabela);
            doc.close();
            
            JOptionPane.showMessageDialog(null, "Relatório salvo com sucesso");
            String caminho = "C:/SRS/RelatorioProduto.pdf";
            Desktop.getDesktop().open(new File(caminho));
        } catch (DocumentException e) {
            e.printStackTrace();
        } catch (IOException exx) {
            exx.printStackTrace();
            JOptionPane.showMessageDialog(null, "Documento de Requisitos aberto. Feche para gerar um novo.");
        }

      }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtAlterar;
    private javax.swing.JButton BtCancelar;
    private javax.swing.JButton BtEditar;
    private javax.swing.JButton BtExcluir;
    private javax.swing.JButton BtNovo;
    private javax.swing.JButton BtRelatorio;
    private javax.swing.JButton BtSalvar;
    private javax.swing.JTextField TxCodProduto;
    private javax.swing.JTextField TxDescreveProduto;
    private javax.swing.JTextField TxPrecoProd;
    private javax.swing.JTextField TxPrecoProdVenda;
    private javax.swing.JTextField TxQtdProd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblCliente;
    // End of variables declaration//GEN-END:variables
}
